version: "1"
services:
  hadoop:
    image: sequenceiq/hadoop-docker
  spark:
    image: bitnami/spark
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"